"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'es' | 'zh' | 'hi' | 'ar';

interface TranslationContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        "nav.render": "Render",
        "nav.inpaint": "Inpaint",
        "nav.upscale": "Upscale",
        "nav.pricing": "Pricing",
        "nav.faq": "FAQ",
        "nav.upgrade": "Upgrade to PRO",
        "nav.furniture": "Furniture",
        "nav.color": "Color Match",
        "nav.magic": "Magic Editor",
        "magic.title": "Magic Editor",
        "magic.subtitle": "Edit your room with natural language",
        "magic.placeholder": "Describe what to change (e.g. 'remove the rug', 'make walls blue')",
        "magic.generate": "Magic Edit",
        "magic.upload_label": "Upload Room Photo",
        "color.title": "Color Match",
        "color.subtitle": "Instantly change your room's color palette",
        "color.palette_label": "Select Palette",
        "color.upload_label": "Upload Room Photo",
        "color.generate": "Apply Colors",
        "color.custom_prompt": "Custom colors (e.g. 'navy blue and gold')",
        "furniture.title": "Furniture Placement",
        "furniture.subtitle": "Add objects to your room naturally",
        "furniture.room_label": "Room Photo",
        "furniture.object_label": "Furniture Object",
        "furniture.generate": "Place Object",
        "furniture.upload_room": "Upload main room photo",
        "furniture.upload_object": "Upload furniture photo",
        "furniture.prompt_hint": "E.g. Place this chair in the corner...",
        "hero.title": "Your Dream Room in Seconds",
        "hero.subtitle": "Transform your space with AI. Upload a photo and see the magic happen instantly.",
        "hero.upload": "Transform My Room",
        "stats.users": "Happy Users",
        "stats.redesigns": "Room Redesigns",
        "features.title": "Why RoomCraft App?",
        "features.subtitle": "Experience the future of interior design with our powerful AI features.",
        "pricing.title": "Simple, Transparent Pricing",
        "pricing.desc": "Choose the plan that fits your needs",
        "pricing.mostPopular": "Most Popular",
        "pricing.weekly": "Weekly Unlimited",
        "pricing.monthly": "Monthly Unlimited",
        "pricing.yearly": "Yearly Unlimited",
        "btn.startTrial": "Start 3-Day Free Trial",
        "faq.title": "Frequently Asked Questions",
        "footer.product": "Product",
        "footer.company": "Company",
        "footer.legal": "Legal",
        "footer.connect": "Connect",
        "styles.title": "Choose Your Style",
        "styles.modern": "Modern Minimalist",
        "styles.scandinavian": "Scandinavian",
        "styles.industrial": "Industrial",
        "styles.midcentury": "Mid-Century Modern",
        "styles.bohemian": "Bohemian",
        "styles.coastal": "Coastal Mediterranean",
        "styles.farmhouse": "Rustic Farmhouse",
        "styles.artdeco": "Luxury Art Deco",
        "styles.japanese": "Japanese Zen",
        "styles.mediterranean": "Mediterranean",
        "styles.rustic": "Rustic",
        "styles.contemporary": "Contemporary",
        "styles.japandi": "Japandi",
        "styles.dark": "Minimalist Dark",
        "styles.retro": "Retro 70s",
        "features.f1.title": "Every Space. Every Style.",
        "features.f1.desc": "From living rooms to gardens. Modern to vintage. Your vision, instantly visualized.",
        "features.f2.title": "Professional Quality",
        "features.f2.desc": "Export in stunning 4K resolution. Ready for presentations or social media.",
        "features.f3.title": "Real-Time Preview",
        "features.f3.desc": "Watch your space transform before your eyes. No waiting, no guessing.",
        "gallery.title": "Real Transformations",
        "gallery.desc": "See what others have created in seconds",
        "gallery.indicator": "designs generated in the last hour",
        "testimonials.title": "Loved by Designers & Homeowners",
        "testimonials.subtitle": "See what our community has to say",
        "testimonials.t1.name": "Sarah Mitchell",
        "testimonials.t1.role": "Interior Designer",
        "testimonials.t1.location": "New York, USA",
        "testimonials.t1.content": "This tool has completely transformed how I present concepts to clients. The AI generates stunning visuals in seconds that would take me hours to create manually.",
        "testimonials.t2.name": "James Thompson",
        "testimonials.t2.role": "Real Estate Agent",
        "testimonials.t2.location": "London, UK",
        "testimonials.t2.content": "Game changer for staging virtual tours. My listings now showcase potential transformations instantly. Clients love seeing what spaces could become.",
        "testimonials.t3.name": "Carlos Rodríguez",
        "testimonials.t3.role": "Architect",
        "testimonials.t3.location": "Buenos Aires, Argentina",
        "testimonials.t3.content": "Incredible tool for visualizing projects. My clients are impressed with the quality and speed of the renders. Totally recommended!",
        "controls.upload.title": "Upload a photo",
        "controls.upload.tips": "Tips 💡",
        "controls.upload.ready": "Ready to render",
        "controls.upload.button": "Upload a file",
        "controls.upload.desc": "Click to select or drag & drop. JPG, PNG up to 10MB",
        "controls.settings.roomType": "Select room type",
        "controls.settings.commercial": "Commercial",
        "controls.settings.residential": "Residential",
        "controls.settings.perspective": "Perspective",
        "controls.settings.interior": "Interior",
        "controls.settings.exterior": "Exterior",
        "controls.settings.aesthetic": "Design Aesthetic",
        "controls.settings.promptLabel": "Additional Prompt (Optional)",
        "controls.settings.promptPlaceholder": "Write your prompt here...",
        "controls.btn.rendering": "Rendering...",
        "controls.btn.render": "Render Interior",
        "styles.cyberpunk": "Cyberpunk Neon",
        "styles.tropical": "Tropical Oasis",
        "preview.scanning": "Scanning...",
        "preview.processing": "AI PROCESSING",
        "preview.geometry": "Scanning geometry...",
        "preview.noResults": "No Results Yet",
        "preview.desc": "Fill in the form on the left by uploading an image and selecting a style to generate your first interior.",
        "gallery.dashboard.title": "Renders Gallery",
        "gallery.view": "View",
        "gallery.search_placeholder": "Search your designs...",
        "gallery.filter.all": "All",
        "gallery.filter.render": "Renders",
        "gallery.filter.furniture": "Furniture",
        "gallery.filter.color": "Color",
        "gallery.filter.magic": "Magic",
        "gallery.delete_confirm": "Are you sure you want to delete this design?",
        "gallery.delete_btn": "Delete",
        "gallery.cancel_btn": "Cancel",
        "gallery.empty": "No renders yet. Create your first design to see it here!",
        "hero.viewExamples": "View Examples",
        "hero.trust.users": "users",
        "hero.trust.rooms": "rooms redesigned",
        "hero.trust.rating": "rating",
        "hero.rendering": "Rendering your future home...",
        "pricing.f.unlimited": "Unlimited generations",
        "pricing.f.4k": "4K quality exports",
        "pricing.f.allRooms": "All room types",
        "pricing.f.emailSupport": "Email support",
        "pricing.f.everythingWeekly": "Everything in Weekly",
        "pricing.f.priority": "Priority processing",
        "pricing.f.styles": "32+ design styles",
        "pricing.f.prioritySupport": "Priority support",
        "pricing.f.team": "Team collaboration",
        "pricing.f.everythingMonthly": "Everything in Monthly",
        "pricing.f.customAi": "Custom AI training",
        "pricing.f.api": "API access",
        "pricing.f.dedicatedSupport": "Dedicated support",
        "pricing.f.whiteLabel": "White-label option",
        "pricing.desc.weekly": "Perfect for trying out",
        "pricing.desc.monthly": "Most popular choice",
        "pricing.desc.yearly": "Best value",
        "pricing.trial": "3-DAY FREE TRIAL",
        "pricing.savings": "SAVE 60%",
        "pricing.faq.q1": "Can I cancel anytime?",
        "pricing.faq.a1": "Yes, cancel with one click",
        "pricing.faq.q2": "What happens after trial?",
        "pricing.faq.a2": "Nothing. We'll notify you first",
        "pricing.faq.q3": "Do you offer refunds?",
        "pricing.faq.a3": "Full refund within 3 days",
        "faq.subtitle": "Everything you need to know about RoomCraft App",
        "faq.cta.text": "Still have questions?",
        "faq.cta.btn": "Contact our support team",
        "faq.q1": "How does RoomCraft App work?",
        "faq.a1": "Simply upload a photo of your room, select a design style, and our AI will generate a photorealistic redesign of your space in seconds.",
        "faq.q2": "Is there a free trial?",
        "faq.a2": "Yes! We offer a 3-day free trial on our Monthly and Yearly plans so you can experience the full power of RoomCraft App.",
        "faq.q3": "Can I cancel my subscription?",
        "faq.a3": "Absolutely. You can cancel your subscription at any time through your account settings or by contacting our support.",
        "faq.q4": "What file formats are supported?",
        "faq.a4": "We support JPG and PNG files up to 10MB in size for room uploads.",
        "faq.q5": "Can I use the designs commercially?",
        "faq.a5": "Yes, our PRO plans include commercial licenses for all generated designs.",
        "faq.q6": "How many renders can I generate?",
        "faq.a6": "Our PRO plans offer unlimited generations. Free users are subject to a daily limit.",
        "faq.q7": "Is my data secure?",
        "faq.a7": "Yes, we use industry-standard encryption and security protocols to protect your data and photos.",
        "faq.q8": "Do you offer customer support?",
        "faq.a8": "Yes, we offer email support for all users and priority support for our PRO members.",
        "gallery.cta": "Try this style",
        "hero.new_title_1": "2M+ Rooms Redesigned.",
        "hero.new_title_2": "Your Next Design in 1 Second",
        "hero.new_subtitle": "Upload a photo and watch the magic in real-time. Transform any space with professional-grade AI.",
        "hero.pill.free": "Free",
        "hero.pill.no_reg": "No registration",
        "hero.pill.one_sec": "1 second",
        "hero.cta_main": "Transform Your Space Now",
        "gallery.new_title": "Inspirational Transformations",
        "gallery.new_subtitle": "Your room could be next.",
        "gallery.filter.kitchens": "Kitchens",
        "gallery.filter.bedrooms": "Bedrooms",
        "gallery.filter.bathrooms": "Bathrooms",
        "gallery.filter.living": "Living Rooms",
        "gallery.badge.popular": "MOST POPULAR",
        "gallery.badge.wow": "WOW FACTOR",
        "gallery.badge.elegant": "ELEGANT STYLE",
        "gallery.badge.modern": "MODERNIST",
        "gallery.label.before": "Before",
        "gallery.label.after": "After (AI)",
        "gallery.cta_try": "Try This Style",
        "styles.multi.title": "Don't Limit Yourself to One Style",
        "styles.multi.subtitle": "Same room. 3 different styles.",
        "styles.multi.before": "Original",
        "styles.multi.after": "AFTER",
        "styles.multi.cta": "Try With My Photo",
        "dashboard.templates.or_start": "Or Start with a Template",
        "dashboard.templates.living": "Living Room",
        "dashboard.templates.bedroom": "Bedroom",
        "dashboard.templates.room": "Empty Room",
        "dashboard.templates.kitchen": "Old Kitchen",
        "dashboard.styles.choose_title": "Choose Style",
        "dashboard.form.prompt_label": "Describe what you want (Optional)",
        "dashboard.form.prompt_placeholder": "Modern minimalist living room with white furniture...",
        "dashboard.form.generate_btn": "Generate Design",
        "dashboard.form.analyzing": "Analyzing space...",
        "loader.scanning": "Scanning environment...",
        "loader.processing": "Processing room structure...",
        "loader.generating": "Generating your design...",
        "loader.finalizing": "Finalizing touches...",
        "dashboard.preview.start_new": "Start New",
        "dashboard.preview.download": "Download Design",
        "dashboard.upload.click": "Click to Upload",
        "dashboard.upload.drag": "or drag and drop your photo here",
        "dashboard.upload.change": "Change Photo",
        "dashboard.preview.empty": "Your masterpiece will appear here",
        "dashboard.community.title": "Community Inspirations",
        "dashboard.community.empty_hint": "No history yet. Start designing to see your work here!",
        "dashboard.teaser.title": "Unlock Your Professional Design",
        "dashboard.teaser.subtitle": "Your masterpiece is ready. Upgrade to PRO to view the high-quality result instantly.",
        "dashboard.teaser.button": "Unlock Design Now",
    },
    es: {
        "nav.render": "Renderizar",
        "nav.inpaint": "Retocar",
        "nav.upscale": "Escalar",
        "nav.pricing": "Precios",
        "nav.faq": "Preguntas",
        "nav.upgrade": "Mejorar a PRO",
        "hero.title": "Tu Habitación Soñada en Segundos",
        "hero.subtitle": "Transforma tu espacio con IA. Sube una foto y mira la magia ocurrir al instante.",
        "hero.upload": "Transformar Mi Habitación",
        "stats.users": "Usuarios Felices",
        "stats.redesigns": "Rediseños",
        "features.title": "¿Por qué RoomCraft App?",
        "features.subtitle": "Experimenta el futuro del diseño de interiores con nuestras potentes funciones de IA.",
        "pricing.title": "Precios Simples y Transparentes",
        "pricing.desc": "Elige el plan que mejor se adapte a ti",
        "pricing.mostPopular": "Más Popular",
        "pricing.weekly": "Semanal Ilimitado",
        "pricing.monthly": "Mensual Ilimitado",
        "pricing.yearly": "Anual Ilimitado",
        "btn.startTrial": "Prueba Gratis de 3 Días",
        "faq.title": "Preguntas Frecuentes",
        "footer.product": "Producto",
        "footer.company": "Empresa",
        "footer.legal": "Legal",
        "footer.connect": "Conectar",
        "styles.title": "Elige Tu Estilo",
        "styles.modern": "Minimalista Moderno",
        "styles.scandinavian": "Escandinavo",
        "styles.industrial": "Industrial",
        "styles.midcentury": "Moderno de Mitad de Siglo",
        "styles.bohemian": "Bohemio",
        "styles.mediterranean": "Mediterráneo",
        "styles.rustic": "Rústico",
        "styles.contemporary": "Contemporáneo",
        "styles.coastal": "Costero Mediterráneo",
        "styles.farmhouse": "Rústico Moderno",
        "styles.artdeco": "Art Déco Lujo",
        "styles.japanese": "Zen Japonés",
        "styles.japandi": "Japandi",
        "styles.dark": "Minimalista Oscuro",
        "styles.retro": "Retro 70s",
        "features.f1.title": "Cualquier Espacio. Cualquier Estilo.",
        "features.f1.desc": "Desde salas hasta jardines. De moderno a vintage. Tu visión, visualizada al instante.",
        "features.f2.title": "Calidad Profesional",
        "features.f2.desc": "Exporta en impresionante resolución 4K. Listo para presentaciones o redes sociales.",
        "features.f3.title": "Vista Previa en Tiempo Real",
        "features.f3.desc": "Mira tu espacio transformarse ante tus ojos. Sin esperas ni adivinanzas.",
        "gallery.title": "Transformaciones Reales",
        "gallery.desc": "Mira lo que otros han creado en segundos",
        "gallery.indicator": "diseños generados en la última hora",
        "testimonials.title": "Amado por Diseñadores y Propietarios",
        "testimonials.subtitle": "Mira lo que nuestra comunidad tiene para decir",
        "testimonials.t1.name": "Sarah Mitchell",
        "testimonials.t1.role": "Diseñadora de Interiores",
        "testimonials.t1.location": "Nueva York, EE.UU.",
        "testimonials.t1.content": "Esta herramienta ha transformado completamente cómo presento conceptos a los clientes. La IA genera visuales impresionantes en segundos que me llevarían horas crear manualmente.",
        "testimonials.t2.name": "James Thompson",
        "testimonials.t2.role": "Agente Inmobiliario",
        "testimonials.t2.location": "Londres, Reino Unido",
        "testimonials.t2.content": "Cambiador de juego para el home staging virtual. Mis anuncios ahora muestran transformaciones potenciales al instante. A los clientes les encanta ver en qué podrían convertirse los espacios.",
        "testimonials.t3.name": "Carlos Rodríguez",
        "testimonials.t3.role": "Arquitecto",
        "testimonials.t3.location": "Buenos Aires, Argentina",
        "testimonials.t3.content": "Increíble herramienta para visualizar proyectos. Mis clientes quedan impresionados con la calidad y velocidad de los renders. ¡Totalmente recomendado!",
        "controls.upload.title": "Sube una foto",
        "controls.upload.tips": "Consejos 💡",
        "controls.upload.ready": "Listo para renderizar",
        "controls.upload.button": "Subir archivo",
        "controls.upload.desc": "Haz clic para seleccionar o arrastra y suelta. JPG, PNG hasta 10MB",
        "controls.settings.roomType": "Elige tipo de habitación",
        "controls.settings.commercial": "Comercial",
        "controls.settings.residential": "Residencial",
        "controls.settings.perspective": "Perspectiva",
        "controls.settings.interior": "Interior",
        "controls.settings.exterior": "Exterior",
        "controls.settings.aesthetic": "Estética de Diseño",
        "controls.settings.promptLabel": "Indicación Adicional (Opcional)",
        "controls.settings.promptPlaceholder": "Escribe tu indicación aquí...",
        "controls.btn.rendering": "Renderizando...",
        "controls.btn.render": "Renderizar Interior",
        "styles.cyberpunk": "Cyberpunk Neón",
        "styles.tropical": "Oasis Tropical",
        "preview.scanning": "Escaneando...",
        "preview.processing": "PROCESAMIENTO IA",
        "preview.geometry": "Escaneando geometría...",
        "preview.noResults": "Sin resultados aún",
        "preview.desc": "Completa el formulario a la izquierda subiendo una imagen y seleccionando un estilo para generar tu primer interior.",
        "gallery.dashboard.title": "Galería de Renders",
        "gallery.view": "Ver",
        "gallery.empty": "Sin renders aún. ¡Crea tu primer diseño para verlo aquí!",
        "hero.viewExamples": "Ver Ejemplos",
        "hero.trust.users": "usuarios",
        "hero.trust.rooms": "habitaciones rediseñadas",
        "hero.trust.rating": "calificación",
        "hero.rendering": "Renderizando tu futuro hogar...",
        "pricing.f.unlimited": "Generaciones ilimitadas",
        "pricing.f.4k": "Exportaciones en calidad 4K",
        "pricing.f.allRooms": "Todos los tipos de habitaciones",
        "pricing.f.emailSupport": "Soporte por correo",
        "pricing.f.everythingWeekly": "Todo lo del plan Semanal",
        "pricing.f.priority": "Procesamiento prioritario",
        "pricing.f.styles": "Más de 32 estilos de diseño",
        "pricing.f.prioritySupport": "Soporte prioritario",
        "pricing.f.team": "Colaboración en equipo",
        "pricing.f.everythingMonthly": "Todo lo del plan Mensual",
        "pricing.f.customAi": "Entrenamiento de IA personalizado",
        "pricing.f.api": "Acceso a la API",
        "pricing.f.dedicatedSupport": "Soporte dedicado",
        "pricing.f.whiteLabel": "Opción de marca blanca",
        "pricing.desc.weekly": "Ideal para probar",
        "pricing.desc.monthly": "La opción más popular",
        "pricing.desc.yearly": "El mejor valor",
        "pricing.trial": "PRUEBA GRATIS DE 3 DÍAS",
        "pricing.savings": "AHORRA 60%",
        "pricing.faq.q1": "¿Puedo cancelar cuando quiera?",
        "pricing.faq.a1": "Sí, cancela con un solo clic",
        "pricing.faq.q2": "¿Qué pasa después de la prueba?",
        "pricing.faq.a2": "Nada. Te avisaremos primero",
        "pricing.faq.q3": "¿Ofrecen reembolsos?",
        "pricing.faq.a3": "Reembolso total en 3 días",
        "faq.subtitle": "Todo lo que necesitas saber sobre RoomCraft App",
        "faq.cta.text": "¿Aún tienes preguntas?",
        "faq.cta.btn": "Contacta con soporte",
        "faq.q1": "¿Cómo funciona RoomCraft App?",
        "faq.a1": "Simplemente sube una foto de tu habitación, selecciona un estilo de diseño y nuestra IA generará un rediseño fotorrealista de tu espacio en segundos.",
        "faq.q2": "¿Hay una prueba gratuita?",
        "faq.a2": "¡Sí! Ofrecemos una prueba gratuita de 3 días en nuestros planes Mensual y Anual para que experimentes todo el poder de RoomCraft App.",
        "faq.q3": "¿Puedo cancelar mi suscripción?",
        "faq.a3": "Absolutamente. Puedes cancelar tu suscripción en cualquier momento a través de la configuración de tu cuenta o contactando a nuestro soporte.",
        "faq.q4": "¿Qué formatos de archivo son compatibles?",
        "faq.a4": "Soportamos archivos JPG y PNG de hasta 10MB para las cargas de habitaciones.",
        "faq.q5": "¿Puedo usar los diseños comercialmente?",
        "faq.a5": "Sí, nuestros planes PRO incluyen licencias comerciales para todos los diseños generados.",
        "faq.q6": "¿Cuántos renders puedo generar?",
        "faq.a6": "Nuestros planes PRO ofrecen generaciones ilimitadas. Los usuarios gratuitos están sujetos a un límite diario.",
        "faq.q7": "¿Son seguros mis datos?",
        "faq.a7": "Sí, utilizamos cifrado y protocolos de seguridad estándar de la industria para proteger tus datos y fotos.",
        "faq.q8": "¿Ofrecen soporte al cliente?",
        "faq.a8": "Sí, ofrecemos soporte por correo electrónico para todos los usuarios y soporte prioritario para nuestros miembros PRO.",
        "gallery.cta": "Probar este estilo",
        "hero.new_title_1": "2M+ Habitaciones Rediseñadas.",
        "hero.new_title_2": "Tu Próximo Diseño en 1 Segundo",
        "hero.new_subtitle": "Sube una foto y mira la magia en tiempo real. Transforma cualquier espacio con inteligencia artificial de nivel profesional.",
        "hero.pill.free": "Gratis",
        "hero.pill.no_reg": "Sin registro",
        "hero.pill.one_sec": "1 segundo",
        "hero.cta_main": "Transforma Tu Espacio Ahora",
        "gallery.new_title": "Transformaciones que Inspiran",
        "gallery.new_subtitle": "Tu habitación podría ser la próxima.",
        "gallery.filter.all": "Todos",
        "gallery.filter.kitchens": "Cocinas",
        "gallery.filter.bedrooms": "Dormitorios",
        "gallery.filter.bathrooms": "Baños",
        "gallery.filter.living": "Salas",
        "gallery.badge.popular": "MÁS POPULAR",
        "gallery.badge.wow": "WOW FACTOR",
        "gallery.badge.elegant": "ESTILO ELEGANTE",
        "gallery.badge.modern": "MODERNISTA",
        "gallery.label.before": "Antes",
        "gallery.label.after": "Después (IA)",
        "gallery.cta_try": "Probar Este Estilo",
        "styles.multi.title": "No te Limites a Un Solo Estilo",
        "styles.multi.subtitle": "Mismo baño. 3 estilos diferentes.",
        "styles.multi.before": "Original",
        "styles.multi.after": "DESPUÉS",
        "styles.multi.cta": "Probar Con Mi Foto",
        "dashboard.templates.or_start": "O empieza con una plantilla",
        "dashboard.templates.living": "Sala de estar",
        "dashboard.templates.bedroom": "Dormitorio",
        "dashboard.templates.room": "Habitación vacía",
        "dashboard.templates.kitchen": "Cocina antigua",
        "dashboard.styles.choose_title": "Elige un estilo",
        "dashboard.form.prompt_label": "Describe lo que quieres (Opcional)",
        "dashboard.form.prompt_placeholder": "Sala de estar minimalista moderna con muebles blancos...",
        "dashboard.form.generate_btn": "Generar Diseño",
        "dashboard.form.analyzing": "Analizando espacio...",
        "dashboard.preview.start_new": "Empezar de nuevo",
        "dashboard.preview.download": "Descargar Diseño",
        "dashboard.upload.click": "Haz clic para subir",
        "dashboard.upload.drag": "o arrastra y suelta tu foto aquí",
        "dashboard.upload.change": "Cambiar Foto",
        "dashboard.preview.empty": "Tu obra maestra aparecerá aquí",
        "dashboard.community.title": "Inspiraciones de la Comunidad",
        "dashboard.community.empty_hint": "Sin historial aún. ¡Empieza a diseñar para ver tu trabajo aquí!",
        "dashboard.teaser.title": "Desbloquea Tu Diseño Profesional",
        "dashboard.teaser.subtitle": "Tu obra maestra está lista. Mejora a PRO para ver el resultado en alta calidad al instante.",
        "dashboard.teaser.button": "Desbloquear Diseño Ahora",
    },
    zh: {
        "nav.render": "渲染",
        "nav.inpaint": "修补",
        "nav.upscale": "放大",
        "nav.pricing": "价格",
        "nav.faq": "常见问题",
        "nav.upgrade": "升级到 PRO",
        "hero.title": "几秒钟内打造您的梦想房间",
        "hero.subtitle": "利用AI改造您的空间。上传照片，立即可见神奇效果。",
        "hero.upload": "改造我的房间",
        "stats.users": "快乐用户",
        "stats.redesigns": "房间重新设计",
        "features.title": "为什么选择 RoomCraft App？",
        "features.subtitle": "利用我们强大的 AI 功能体验室内设计的未来。",
        "pricing.title": "简单透明的价格",
        "pricing.desc": "选择适合您的计划",
        "pricing.mostPopular": "最受欢迎",
        "pricing.weekly": "每周无限",
        "pricing.monthly": "每月无限",
        "pricing.yearly": "每年无限",
        "btn.startTrial": "开始 3 天免费试用",
        "faq.title": "常见问题",
        "footer.product": "产品",
        "footer.company": "公司",
        "footer.legal": "法律",
        "footer.connect": "联系",
        "styles.title": "选择您的风格",
        "styles.modern": "现代极简主义",
        "styles.scandinavian": "北欧风格",
        "styles.industrial": "工业风",
        "styles.midcentury": "世纪中期现代风",
        "styles.bohemian": "波西米亚风",
        "styles.japanese": "日式禅风",
        "styles.mediterranean": "地中海风格",
        "styles.rustic": "乡村风",
        "styles.contemporary": "当代风格",
        "styles.artdeco": "奢华装饰艺术",
        "styles.japandi": "Japandi 风格",
        "styles.farmhouse": "乡村农舍",
        "styles.dark": "极简暗黑",
        "styles.coastal": "地中海海岸",
        "styles.retro": "70年代复古",

        "features.f1.title": "任何空间。任何风格。",
        "features.f1.desc": "从客厅到花园。从现代到复古。您的愿景，瞬间呈现。",
        "features.f2.title": "专业品质",
        "features.f2.desc": "以惊人的 4K 分辨率导出。适用于演讲或社交媒体。",
        "features.f3.title": "实时预览",
        "features.f3.desc": "亲眼目睹您的空间发生蜕变。无需等待，无需猜测。",
        "gallery.title": "真实蜕变",
        "gallery.desc": "几秒钟内查看他人的创意",
        "gallery.indicator": "过去一小时内生成的设计",
        "testimonials.title": "深受设计师和业主的喜爱",
        "testimonials.subtitle": "看看我们的社区怎么说",
        "testimonials.t1.name": "Sarah Mitchell",
        "testimonials.t1.role": "室内设计师",
        "testimonials.t1.location": "纽约，美国",
        "testimonials.t1.content": "这个工具彻底改变了我向客户展示概念的方式。AI 在几秒钟内生成的令人惊叹的视觉效果，而我手动创建则需要几个小时。",
        "testimonials.t2.name": "James Thompson",
        "testimonials.t2.role": "房地产经纪人",
        "testimonials.t2.location": "伦敦，英国",
        "testimonials.t2.content": "虚拟看房的游戏规则改变者。我的列表现在可以立即展示潜在的转变。客户喜欢看到空间可能变成的样子。",
        "testimonials.t3.name": "Carlos Rodríguez",
        "testimonials.t3.role": "建筑师",
        "testimonials.t3.location": "布宜诺斯艾利斯，阿根廷",
        "testimonials.t3.content": "视觉化项目的出色工具。我的客户对渲染的质量和速度印象深刻。完全推荐！",
        "controls.upload.title": "上传照片",
        "controls.upload.tips": "提示 💡",
        "controls.upload.ready": "准备渲染",
        "controls.upload.button": "上传文件",
        "controls.upload.desc": "点击选择或拖放。JPG, PNG 最高 10MB",
        "controls.settings.roomType": "选择房间类型",
        "controls.settings.commercial": "商业",
        "controls.settings.residential": "住宅",
        "controls.settings.perspective": "透视图",
        "controls.settings.interior": "室内",
        "controls.settings.exterior": "室外",
        "controls.settings.aesthetic": "设计美学",
        "controls.settings.promptLabel": "附加提示（可选）",
        "controls.settings.promptPlaceholder": "在此输入您的提示...",
        "controls.btn.rendering": "渲染中...",
        "controls.btn.render": "室内渲染",
        "styles.cyberpunk": "赛博朋克霓虹",
        "styles.tropical": "热带绿洲",
        "preview.scanning": "扫描中...",
        "preview.processing": "AI 处理中",
        "preview.geometry": "正在扫描几何结构...",
        "preview.noResults": "尚无结果",
        "preview.desc": "通过上传图片并选择风格来填写左侧的表格，生成您的第一个室内设计。",
        "gallery.dashboard.title": "渲染画廊",
        "gallery.view": "查看",
        "gallery.empty": "尚无渲染图。创建您的第一个设计，在此处查看！",
        "hero.viewExamples": "查看示例",
        "hero.trust.users": "用户",
        "hero.trust.rooms": "房间重新设计",
        "hero.trust.rating": "评分",
        "hero.rendering": "正在渲染您未来的家...",
        "pricing.f.unlimited": "无限生成",
        "pricing.f.4k": "4K 质量导出",
        "pricing.f.allRooms": "所有房间类型",
        "pricing.f.emailSupport": "邮件支持",
        "pricing.f.everythingWeekly": "包含每周计划的所有内容",
        "pricing.f.priority": "优先处理",
        "pricing.f.styles": "32+ 种设计风格",
        "pricing.f.prioritySupport": "优先支持",
        "pricing.f.team": "团队协作",
        "pricing.f.everythingMonthly": "包含每月计划的所有内容",
        "pricing.f.customAi": "自定义 AI 训练",
        "pricing.f.api": "API 访问",
        "pricing.f.dedicatedSupport": "专人支持",
        "pricing.f.whiteLabel": "白标选项",
        "pricing.desc.weekly": "非常适合尝试",
        "pricing.desc.monthly": "最受欢迎的选择",
        "pricing.desc.yearly": "最佳价值",
        "pricing.trial": "3 天免费试用",
        "pricing.savings": "节省 60%",
        "pricing.faq.q1": "我可以随时取消吗？",
        "pricing.faq.a1": "是的，一键取消",
        "pricing.faq.q2": "试用期结束后会发生什么？",
        "pricing.faq.a2": "不会发生任何事情。我们会先通知您",
        "pricing.faq.q3": "你们提供退款吗？",
        "pricing.faq.a3": "3 天内全额退款",
        "faq.subtitle": "关于 RoomCraft App 您需要了解的一切",
        "faq.cta.text": "还有疑问吗？",
        "faq.cta.btn": "联系我们的支持团队",
        "faq.q1": "RoomCraft App 是如何工作的？",
        "faq.a1": "只需上传您的房间照片，选择一种设计风格，我们的 AI 就会在几秒钟内为您生成空间的真实感重设计。",
        "faq.q2": "有免费试用吗？",
        "faq.a2": "是的！我们的月度计和年度计划提供 3 天免费试用，以便您体验 RoomCraft App 的全部功能。",
        "faq.q3": "我可以取消订阅吗？",
        "faq.a3": "当然可以。您可以随时通过帐户设置或联系我们的支持团队来取消订阅。",
        "faq.q4": "支持哪些文件格式？",
        "faq.a4": "我们支持最大 10MB 的 JPG 和 PNG 文件进行房间上传。",
        "faq.q5": "我可以将设计用于商业用途吗？",
        "faq.a5": "是的，我们的 PRO 计划包括所有生成设计的商业许可。",
        "faq.q6": "我可以生成多少次渲染？",
        "faq.a6": "我们的 PRO 计划提供无限生成。免费用户受每日限制。",
        "faq.q7": "我的数据安全吗？",
        "faq.a7": "是的，我们使用行业标准的加密和安全协议来保护您的数据和照片。",
        "faq.q8": "你们提供客户支持吗？",
        "faq.a8": "是的，我们为所有用户提供电子邮件支持，并为我们的 PRO 会员提供优先支持。",
        "gallery.cta": "尝试此风格",
        "hero.new_title_1": "2M+ 房间已重新设计。",
        "hero.new_title_2": "1秒内完成您的下个设计",
        "hero.new_subtitle": "上传照片，实时观看魔法。利用专业级AI改变任何空间。",
        "hero.pill.free": "免费",
        "hero.pill.no_reg": "无需注册",
        "hero.pill.one_sec": "1秒",
        "hero.cta_main": "立即改变您的空间",
        "gallery.new_title": "激发灵感的蜕变",
        "gallery.new_subtitle": "您的房间可能是下一个。",
        "gallery.filter.all": "全部",
        "gallery.filter.kitchens": "厨房",
        "gallery.filter.bedrooms": "卧室",
        "gallery.filter.bathrooms": "浴室",
        "gallery.filter.living": "客厅",
        "gallery.badge.popular": "最受欢迎",
        "gallery.badge.wow": "惊艳效果",
        "gallery.badge.elegant": "优雅风格",
        "gallery.badge.modern": "现代主义",
        "gallery.label.before": "之前",
        "gallery.label.after": "之后 (AI)",
        "gallery.cta_try": "尝试此风格",
        "styles.multi.title": "不要局限于一种风格",
        "styles.multi.subtitle": "同一个房间。3种不同风格。",
        "styles.multi.before": "原图",
        "styles.multi.after": "之后",
        "styles.multi.cta": "尝试我的照片",
        "dashboard.templates.or_start": "或从模板开始",
        "dashboard.templates.living": "客厅",
        "dashboard.templates.bedroom": "卧室",
        "dashboard.templates.room": "空房间",
        "dashboard.templates.kitchen": "旧厨房",
        "dashboard.styles.choose_title": "选择风格",
        "dashboard.form.prompt_label": "描述你想要的 (可选)",
        "dashboard.form.prompt_placeholder": "带白色家具的现代简约客厅...",
        "dashboard.form.generate_btn": "生成设计",
        "dashboard.form.analyzing": "分析空间...",
        "dashboard.preview.start_new": "重新开始",
        "dashboard.preview.download": "下载设计",
        "dashboard.upload.click": "点击上传",
        "dashboard.upload.drag": "或将照片拖放到此处",
        "dashboard.upload.change": "更改照片",
        "dashboard.preview.empty": "你的杰作将出现在这里",
        "dashboard.community.title": "社区灵感",
        "dashboard.community.empty_hint": "还没有历史记录。开始设计在这里查看你的作品！",
    },
    hi: {
        "nav.render": "रेंडर",
        "nav.inpaint": "इनपेंट",
        "nav.upscale": "अपस्केल",
        "nav.pricing": "मूल्य निर्धारण",
        "nav.faq": "सामान्य प्रश्न",
        "nav.upgrade": "PRO में अपग्रेड करें",
        "hero.title": "सेकंड में आपका सपनो का कमरा",
        "hero.subtitle": "AI के साथ अपनी जगह बदलें। एक फोटो अपलोड करें और तुरंत जादू देखें।",
        "hero.upload": "मेरा कमरा बदलें",
        "stats.users": "खुश उपयोगकर्ता",
        "stats.redesigns": "कमरा रिडिजाइन",
        "features.title": "RoomCraft App क्यों?",
        "features.subtitle": "हमारी शक्तिशाली AI विशेषताओं के साथ इंटीरियर डिज़ाइन के भविष्य का अनुभव करें।",
        "pricing.title": "सरल, पारदर्शी मूल्य निर्धारण",
        "pricing.desc": "वह योजना चुनें जो आपकी आवश्यकताओं के अनुरूप हो",
        "pricing.mostPopular": "सर्वाधिक लोकप्रिय",
        "pricing.weekly": "साप्ताहिक असीमित",
        "pricing.monthly": "मासिक असीमित",
        "pricing.yearly": "वार्षिक असीमित",
        "btn.startTrial": "3-दिन का निःशुल्क परीक्षण शुरू करें",
        "faq.title": "अक्सर पूछे जाने वाले प्रश्न",
        "footer.product": "उत्पाद",
        "footer.company": "कंपनी",
        "footer.legal": "कानूनी",
        "footer.connect": "जुड़ें",
        "styles.title": "अपनी शैली चुनें",
        "styles.modern": "आधुनिक न्यूनतम",
        "styles.scandinavian": "स्कैंडिनेवियाई",
        "styles.industrial": "औद्योगिक",
        "styles.midcentury": "मिड-सेंचुरी मॉडर्न",
        "styles.bohemian": "बोहेमियन",
        "styles.coastal": "तटीय",
        "styles.farmhouse": "फार्महाउस",
        "styles.artdeco": "आर्ट डेको",
        "styles.japanese": "जापानी ज़ेन",
        "styles.mediterranean": "भूमध्यसागरीय",
        "styles.rustic": "देहाती",
        "styles.contemporary": "समकालीन",
        "features.f1.title": "हर जगह। हर शैली।",
        "features.f1.desc": "लिविंग रूम से लेकर गार्डन तक। आधुनिक से लेकर विंटेज तक। आपकी कल्पना, तुरंत साकार।",
        "features.f2.title": "पेशेवर गुणवत्ता",
        "features.f2.desc": "शानदार 4K रिज़ॉल्यूशन में एक्सपोर्ट करें। प्रेजेंटेशन या सोशल मीडिया के लिए तैयार।",
        "features.f3.title": "रियल-टाइम प्रीव्यू",
        "features.f3.desc": "अपनी आँखों के सामने अपनी जगह को बदलते हुए देखें। कोई इंतज़ार नहीं, कोई अंदाज़ा नहीं।",
        "gallery.title": "वास्तविक बदलाव",
        "gallery.desc": "देखें कि अन्य लोगों ने सेकंड में क्या बनाया है",
        "gallery.indicator": "पिछले एक घंटे में उत्पन्न डिज़ाइन",
        "testimonials.title": "डिजाइनरों और घर के मालिकों द्वारा पसंद किया गया",
        "testimonials.subtitle": "देखें कि हमारे समुदाय का क्या कहना है",
        "testimonials.t1.name": "सारा मिचेल",
        "testimonials.t1.role": "इंटीरियर डिज़ाइनर",
        "testimonials.t1.location": "न्यूयॉर्क, यूएसए",
        "testimonials.t1.content": "इस टूल ने मेरे ग्राहकों को कॉन्सेप्ट पेश करने के तरीके को पूरी तरह से बदल दिया है। AI सेकंडों में आश्चर्यजनक दृश्य उत्पन्न करता है जिन्हें मैन्युअल रूप से बनाने में मुझे घंटों लग जाते थे।",
        "testimonials.t2.name": "जेम्स थॉम्पसन",
        "testimonials.t2.role": "रियल एस्टेट एजेंट",
        "testimonials.t2.location": "लंदन, यूके",
        "testimonials.t2.content": "वर्चुअल टूर के लिए गेम चेंजर। मेरी लिस्टिंग अब तुरंत संभावित बदलावों को प्रदर्शित करती है। ग्राहकों को यह देखना पसंद है कि जगह क्या बन सकती है।",
        "testimonials.t3.name": "कार्लोस रोड्रिगेज",
        "testimonials.t3.role": "आर्किटेक्ट",
        "testimonials.t3.location": "ब्यूनस आयर्स, अर्जेंटीना",
        "testimonials.t3.content": "प्रोजेक्ट्स की कल्पना करने के लिए अविश्वसनीय टूल। मेरे ग्राहक रेंडर की गुणवत्ता और गति से प्रभावित हैं। पूरी तरह से अनुशंसित!",
        "controls.upload.title": "एक फोटो अपलोड करें",
        "controls.upload.tips": "टिप्स 💡",
        "controls.upload.ready": "रेंडर के लिए तैयार",
        "controls.upload.button": "फाइल अपलोड करें",
        "controls.upload.desc": "चुनने के लिए क्लिक करें या ड्रैग एंड ड्रॉप करें। 10MB तक JPG, PNG",
        "controls.settings.roomType": "कमरे का प्रकार चुनें",
        "controls.settings.commercial": "वाणिज्यिक",
        "controls.settings.residential": "आवासीय",
        "controls.settings.perspective": "दृष्टिकोण",
        "controls.settings.interior": "आंतरिक",
        "controls.settings.exterior": "बाहरी",
        "controls.settings.aesthetic": "डिजाइन सौंदर्य",
        "controls.settings.promptLabel": "अतिरिक्त प्रॉम्प्ट (वैकल्पिक)",
        "controls.settings.promptPlaceholder": "अपना प्रॉम्प्ट यहाँ लिखें...",
        "controls.btn.rendering": "रेंडर हो रहा है...",
        "controls.btn.render": "आंतरिक रेंडर करें",
        "styles.cyberpunk": "साइबरपंक नियॉन",
        "styles.tropical": "ट्रॉपिकल ओएसिस",
        "preview.scanning": "स्कैन हो रहा है...",
        "preview.processing": "AI प्रोसेसिंग",
        "preview.geometry": "ज्यामिति स्कैन हो रहा है...",
        "preview.noResults": "अभी तक कोई परिणाम नहीं",
        "preview.desc": "छवि अपलोड करके और अपनी पहली आंतरिक रचना उत्पन्न करने के लिए शैली चुनकर बाईं ओर फॉर्म भरें।",
        "gallery.dashboard.title": "रेंडर गैलरी",
        "gallery.view": "देखें",
        "gallery.empty": "अभी तक कोई रेंडर नहीं। इसे यहाँ देखने के लिए अपना पहला डिज़ाइन बनाएँ!",
        "hero.viewExamples": "उदाहरण देखें",
        "hero.trust.users": "उपयोगकर्ता",
        "hero.trust.rooms": "कमरे रिडिजाइन",
        "hero.trust.rating": "रेटिंग",
        "hero.rendering": "आपके भविष्य के घर को रेंडर किया जा रहा है...",
        "pricing.f.unlimited": "असीमित पीढ़ी",
        "pricing.f.4k": "4K गुणवत्ता निर्यात",
        "pricing.f.allRooms": "सभी कमरे के प्रकार",
        "pricing.f.emailSupport": "ईमेल समर्थन",
        "pricing.f.everythingWeekly": "साप्ताहिक में सब कुछ",
        "pricing.f.priority": "प्राथमिकता प्रसंस्करण",
        "pricing.f.styles": "32+ डिजाइन शैलियाँ",
        "pricing.f.prioritySupport": "प्राथमिकता समर्थन",
        "pricing.f.team": "टीम सहयोग",
        "pricing.f.everythingMonthly": "मासिक में सब कुछ",
        "pricing.f.customAi": "कस्टम AI प्रशिक्षण",
        "pricing.f.api": "API एक्सेस",
        "pricing.f.dedicatedSupport": "समर्पित समर्थन",
        "pricing.f.whiteLabel": "व्हाइट-लेबल विकल्प",
        "pricing.desc.weekly": "आज़माने के लिए बिल्कुल सही",
        "pricing.desc.monthly": "सबसे लोकप्रिय पसंद",
        "pricing.desc.yearly": "सबसे अच्छा मूल्य",
        "pricing.trial": "3-दिवसीय निःशुल्क परीक्षण",
        "pricing.savings": "60% बचाएं",
        "pricing.faq.q1": "क्या मैं किसी भी समय रद्द कर सकता हूँ?",
        "pricing.faq.a1": "हाँ, एक क्लिक से रद्द करें",
        "pricing.faq.q2": "ट्रायल के बाद क्या होता है?",
        "pricing.faq.a2": "कुछ नहीं। हम आपको पहले सूचित करेंगे",
        "pricing.faq.q3": "क्या आप रिफंड देते हैं?",
        "pricing.faq.a3": "3 दिनों के भीतर पूरा रिफंड",
        "faq.subtitle": "RoomCraft App के बारे में वह सब कुछ जो आपको जानना आवश्यक है",
        "faq.cta.text": "अभी भी कोई सवाल है?",
        "faq.cta.btn": "हमारी सहायता टीम से संपर्क करें",
        "faq.q1": "RoomCraft App कैसे काम करता है?",
        "faq.a1": "बस अपने कमरे की फोटो अपलोड करें, एक डिजाइन शैली चुनें, और हमारा AI सेकंड में आपकी जगह का फोटो-यथार्थवादी पुनर्डिज़ाइन तैयार कर देगा।",
        "faq.q2": "क्या कोई निःशुल्क परीक्षण उपलब्ध है?",
        "faq.a2": "हाँ! हम अपनी मासिक और वार्षिक योजनाओं पर 3-दिवसीय निःशुल्क परीक्षण प्रदान करते हैं ताकि आप RoomCraft App की पूरी शक्ति का अनुभव कर सकें。",
        "faq.q3": "क्या मैं अपनी सदस्यता रद्द कर सकता हूँ?",
        "faq.a3": "बिल्कुल। आप अपनी खाता सेटिंग के माध्यम से या हमारे समर्थन से संपर्क करके किसी भी समय अपनी सदस्यता रद्द कर सकते हैं।",
        "faq.q4": "कौन से फ़ाइल स्वरूप समर्थित हैं?",
        "faq.a4": "हम कमरे के अपलोड के लिए 10MB तक की JPG और PNG फ़ाइलों का समर्थन करते हैं।",
        "faq.q5": "क्या मैं डिजाइनों का व्यावसायिक उपयोग कर सकता हूँ?",
        "faq.a5": "हाँ, हमारे PRO प्लान में सभी उत्पन्न डिजाइनों के लिए व्यावसायिक लाइसेंस शामिल हैं।",
        "faq.q6": "मैं कितने रेंडर उत्पन्न कर सकता हूँ?",
        "faq.a6": "हमारी PRO योजनाएँ असीमित पीढ़ी प्रदान करती हैं। मुफ़्त उपयोगकर्ता दैनिक सीमा के अधीन हैं।",
        "faq.q7": "क्या मेरा डेटा सुरक्षित है?",
        "faq.a7": "हाँ, हम आपके डेटा और फ़ोटो की सुरक्षा के लिए उद्योग-मानक एन्क्रिप्शन और सुरक्षा प्रोटोकॉल का उपयोग करते हैं।",
        "faq.q8": "क्या आप ग्राहक सहायता प्रदान करते हैं?",
        "faq.a8": "हाँ, हम सभी उपयोगकर्ताओं के लिए ईमेल सहायता और हमारे PRO सदस्यों के लिए प्राथमिकता सहायता प्रदान करते हैं।",
        "gallery.cta": "इस शैली को आज़माएं",
        "hero.new_title_1": "2M+ कमरे फिर से डिजाइन किए गए।",
        "hero.new_title_2": "1 सेकंड में आपका अगला डिज़ाइन",
        "hero.new_subtitle": "एक फोटो अपलोड करें और रीयल-टाइम में जादू देखें। पेशेवर-ग्रेड AI के साथ किसी भी स्थान को बदलें।",
        "hero.pill.free": "नि: शुल्क",
        "hero.pill.no_reg": "कोई पंजीकरण नहीं",
        "hero.pill.one_sec": "1 सेकंड",
        "hero.cta_main": "अभी अपनी जगह बदलें",
        "gallery.new_title": "प्रेरक परिवर्तन",
        "gallery.new_subtitle": "आपका कमरा अगला हो सकता है।",
        "gallery.filter.all": "सभी",
        "gallery.filter.kitchens": "रसोई",
        "gallery.filter.bedrooms": "शयनकक्ष",
        "gallery.filter.bathrooms": "स्नानघर",
        "gallery.filter.living": "लिविंग रूम",
        "gallery.badge.popular": "सबसे लोकप्रिय",
        "gallery.badge.wow": "वाह कारक",
        "gallery.badge.elegant": "शानदार शैली",
        "gallery.badge.modern": "आधुनिकतावादी",
        "gallery.label.before": "पहले",
        "gallery.label.after": "बाद में (AI)",
        "gallery.cta_try": "इस शैली को आजमाएं",
        "styles.multi.title": "अपने आप को एक शैली तक सीमित न रखें",
        "styles.multi.subtitle": "एक ही कमरा। 3 अलग-अलग शैलियाँ।",
        "styles.multi.before": "मूल",
        "styles.multi.after": "बाद में",
        "styles.multi.cta": "मेरी फोटो के साथ आजमाएं",
        "dashboard.templates.or_start": "या टेम्पलेट से शुरू करें",
        "dashboard.templates.living": "लिविंग रूम",
        "dashboard.templates.bedroom": "शयनकक्ष",
        "dashboard.templates.room": "खाली कमरा",
        "dashboard.templates.kitchen": "पुरानी रसोई",
        "dashboard.styles.choose_title": "शैली चुनें",
        "dashboard.form.prompt_label": "बताएं कि आप क्या चाहते हैं (वैकल्पिक)",
        "dashboard.form.prompt_placeholder": "सफेद फर्नीचर के साथ आधुनिक न्यूनतम लिविंग रूम...",
        "dashboard.form.generate_btn": "डिजाइन तैयार करें",
        "dashboard.form.analyzing": "जगह का विश्लेषण हो रहा है...",
        "dashboard.preview.start_new": "नया शुरू करें",
        "dashboard.preview.download": "डिजाइन डाउनलोड करें",
        "dashboard.upload.click": "अपलोड करने के लिए क्लिक करें",
        "dashboard.upload.drag": "या अपनी फोटो यहाँ ड्रैग एंड ड्रॉप करें",
        "dashboard.upload.change": "फोटो बदलें",
        "dashboard.preview.empty": "आपकी उत्कृष्ट कृति यहाँ दिखाई देगी",
        "dashboard.community.title": "सामुदायिक प्रेरणा",
        "dashboard.community.empty_hint": "अभी तक कोई इतिहास नहीं है। अपना काम यहाँ देखने के लिए डिजाइनिंग शुरू करें!",
        "dashboard.teaser.title": "अपना पेशेवर डिज़ाइन अनलॉक करें",
        "dashboard.teaser.subtitle": "आपकी उत्कृष्ट कृति तैयार है। उच्च गुणवत्ता परिणाम तुरंत देखने के लिए PRO में अपग्रेड करें।",
        "dashboard.teaser.button": "डिज़ाइन अभी अनलॉक करें",
    },
    ar: {
        "nav.render": "تصيير",
        "nav.inpaint": "ترميم",
        "nav.upscale": "تكبير",
        "nav.pricing": "التسعير",
        "nav.faq": "الأسئلة الشائعة",
        "nav.upgrade": "الترقية الى PRO",
        "hero.title": "غرفة أحلامك في ثوانٍ",
        "hero.subtitle": "حول مساحتك باستخدام الذكاء الاصطناعي. قم بتحميل صورة وشاهد السحر يحدث على الفور.",
        "hero.upload": "حول غرفتي",
        "stats.users": "مستخدمون سعداء",
        "stats.redesigns": "إعادة تصميم الغرف",
        "features.title": "لماذا RoomCraft App؟",
        "features.subtitle": "جرب مستقبل التصميم الداخلي بميزات الذكاء الاصطناعي القوية لدينا.",
        "pricing.title": "تسعير بسيط وشفاف",
        "pricing.desc": "اختر الخطة التي تناسب احتياجاتك",
        "pricing.mostPopular": "الأكثر شيوعًا",
        "pricing.weekly": "أسبوعي غير محدود",
        "pricing.monthly": "شهري غير محدود",
        "pricing.yearly": "سنوي غير محدود",
        "btn.startTrial": "ابدأ إصدار تجريبي مجاني لمدة 3 أيام",
        "faq.title": "أسئلة مكررة",
        "footer.product": "المنتج",
        "footer.company": "الشركة",
        "footer.legal": "قانوني",
        "footer.connect": "تواصل",
        "styles.title": "اختر طرازك",
        "styles.modern": "بسيط حديث",
        "styles.scandinavian": "اسكندنافي",
        "styles.industrial": "صناعي",
        "styles.midcentury": "منتصف القرن",
        "styles.bohemian": "بوهيمي",
        "styles.coastal": "ساحلي",
        "styles.farmhouse": "ريفي عصري",
        "styles.artdeco": "آرت ديكو فاخر",
        "styles.japanese": "زن اليابانية",
        "styles.mediterranean": "بحر متوسط",
        "styles.rustic": "ريفي",
        "styles.contemporary": "معاصر",
        "styles.japandi": "جاباندي",
        "styles.dark": "مينيماليست غامق",
        "styles.retro": "ريترو السبعينات",
        "features.f1.title": "كل مساحة. كل طراز.",
        "features.f1.desc": "من غرف المعيشة إلى الحدائق. من الحديث إلى العتيق. رؤيتك، تتجسد فوراً.",
        "features.f2.title": "جودة احترافية",
        "features.f2.desc": "تصدير بدقة 4K مذهلة. جاهز للعروض التقديمية أو وسائل التواصل الاجتماعي.",
        "features.f3.title": "معاينة فورية",
        "features.f3.desc": "شاهد مساحتك تتحول أمام عينيك. لا انتظار، لا تخمين.",
        "gallery.title": "تحولات حقيقية",
        "gallery.desc": "شاهد ما ابتكره الآخرون في ثوانٍ",
        "gallery.indicator": "تصميم تم إنشاؤه في الساعة الماضية",
        "testimonials.title": "محبوب من قبل المصممين وأصحاب المنازل",
        "testimonials.subtitle": "اكتشف ما يقوله مجتمعنا",
        "testimonials.t1.name": "سارة ميتشل",
        "testimonials.t1.role": "مصممة ديكور",
        "testimonials.t1.location": "نيويورك، الولايات المتحدة",
        "testimonials.t1.content": "لقد غيرت هذه الأداة تماماً طريقة عرضي للمفاهيم للعملاء. ينشئ الذكاء الاصطناعي صوراً مذهلة في ثوانٍ كانت ستستغرق مني ساعات لإنشاءها يدوياً.",
        "testimonials.t2.name": "جيمس ثومبسون",
        "testimonials.t2.role": "وكيل عقارات",
        "testimonials.t2.location": "لندن، المملكة المتحدة",
        "testimonials.t2.content": "مغير قواعد اللعبة للجولات الافتراضية. تعرض قوائمي الآن التحولات المحتملة على الفور. يحب العملاء رؤية ما يمكن أن تصبح عليه المساحات.",
        "testimonials.t3.name": "كارلوس رودريغيز",
        "testimonials.t3.role": "مهندس معماري",
        "testimonials.t3.location": "بوينس آيرس، الأرجنتين",
        "testimonials.t3.content": "أداة مذهلة لتصور المشاريع. ينبهر عملائي بجودة وسرعة التصيير. موصى به تماماً!",
        "controls.upload.title": "تحميل صورة",
        "controls.upload.tips": "نصائح 💡",
        "controls.upload.ready": "جاهز للتصيير",
        "controls.upload.button": "تحميل ملف",
        "controls.upload.desc": "انقر للاختيار أو السحب والإفلات. JPG, PNG حتى 10 ميجابايت",
        "controls.settings.roomType": "اختر نوع الغرفة",
        "controls.settings.commercial": "تجاري",
        "controls.settings.residential": "سكني",
        "controls.settings.perspective": "المنظور",
        "controls.settings.interior": "داخلي",
        "controls.settings.exterior": "خارجي",
        "controls.settings.aesthetic": "جمالية التصميم",
        "controls.settings.promptLabel": "موجه إضافي (اختياري)",
        "controls.settings.promptPlaceholder": "اكتب موجهك هنا...",
        "controls.btn.rendering": "جاري التصيير...",
        "controls.btn.render": "تصيير داخلي",
        "styles.cyberpunk": "سايبربانك نيون",
        "styles.tropical": "واحة استوائية",
        "preview.scanning": "جاري المسح...",
        "preview.processing": "معالجة الذكاء الاصطناعي",
        "preview.geometry": "جاري مسح الهندسة...",
        "preview.noResults": "لا توجد نتائج بعد",
        "preview.desc": "املأ النموذج على اليسار عن طريق تحميل صورة واختيار نمط لتوليد أول تصميم داخلي لك.",
        "gallery.dashboard.title": "معرض التصاميم",
        "gallery.view": "عرض",
        "gallery.empty": "لا توجد تصاميم بعد. أنشئ أول تصميم لك لتراه هنا!",
        "hero.viewExamples": "مشاهدة الأمثلة",
        "hero.trust.users": "مستخدمين",
        "hero.trust.rooms": "غرف معاد تصميمها",
        "hero.trust.rating": "تقييم",
        "hero.rendering": "جاري تصيير منزل أحلامك...",
        "pricing.f.unlimited": "أجيال غير محدودة",
        "pricing.f.4k": "تصدير بجودة 4K",
        "pricing.f.allRooms": "جميع أنواع الغرف",
        "pricing.f.emailSupport": "دعم عبر البريد الإلكتروني",
        "pricing.f.everythingWeekly": "كل شيء في الخطة الأسبوعية",
        "pricing.f.priority": "معالجة ذات أولوية",
        "pricing.f.styles": "أكثر من 32 طرازاً للتصميم",
        "pricing.f.prioritySupport": "دعم ذو أولوية",
        "pricing.f.team": "تعاون الفريق",
        "pricing.f.everythingMonthly": "كل شيء في الخطة الشهرية",
        "pricing.f.customAi": "تدريب خاص للذكاء الاصطناعي",
        "pricing.f.api": "وصول إلى API",
        "pricing.f.dedicatedSupport": "دعم مخصص",
        "pricing.f.whiteLabel": "خيار العلامة البيضاء",
        "pricing.desc.weekly": "مثالي للتجربة",
        "pricing.desc.monthly": "الخيار الأكثر شعبية",
        "pricing.desc.yearly": "أفضل قيمة",
        "pricing.trial": "إصدار تجريبي مجاني لمدة 3 أيام",
        "pricing.savings": "وفر 60%",
        "pricing.faq.q1": "هل يمكنني الإلغاء في أي وقت؟",
        "pricing.faq.a1": "نعم، قم بالإلغاء بنقرة واحدة",
        "pricing.faq.q2": "ماذا يحدث بعد انتهاء الفترة التجريبية؟",
        "pricing.faq.a2": "لا شيء. سنقوم بإخطارك أولاً",
        "pricing.faq.q3": "هل تقدمون استرداداً للأموال؟",
        "pricing.faq.a3": "استرداد كامل في غضون 3 أيام",
        "faq.subtitle": "كل ما تحتاج لمعرفته حول RoomCraft App",
        "faq.cta.text": "لا تزال لديك أسئلة؟",
        "faq.cta.btn": "تواصل مع فريق الدعم",
        "faq.q1": "كيف يعمل RoomCraft App؟",
        "faq.a1": "بساطة، قم بتحميل صورة لغرفتك، واختر طراز التصميم، وسيقوم الذكاء الاصطناعي لدينا بإنشاء إعادة تصميم واقعية لمساحتك في ثوانٍ.",
        "faq.q2": "هل هناك فترة تجريبية مجانية؟",
        "faq.a2": "نعم! نحن نقدم فترة تجريبية مجانية لمدة 3 أيام في خططنا الشهرية والسنوية لتتمكن من تجربة القوة الكاملة لـ RoomCraft App.",
        "faq.q3": "هل يمكنني إلغاء اشتراكي؟",
        "faq.a3": "بالتأكيد. يمكنك إلغاء اشتراكك في أي وقت من خلال إعدادات حسابك أو عن طريق الاتصال بالدعم لدينا.",
        "faq.q4": "ما هي صيغ الملفات المدعومة؟",
        "faq.a4": "نحن ندعم ملفات JPG و PNG حتى حجم 10 ميجابايت لتحميل الصور.",
        "faq.q5": "هل يمكنني استخدام التصاميم تجارياً؟",
        "faq.a5": "نعم، تشمل خطط PRO لدينا تراخيص تجارية لجميع التصاميم المنشأة.",
        "faq.q6": "كم عدد التصاميم التي يمكنني إنشاؤها؟",
        "faq.a6": "تقدم خطط PRO لدينا عدد غير محدود من الأجيال. يخضع المستخدمون المجانيون لحد يومي.",
        "faq.q7": "هل بياناتي آمنة؟",
        "faq.a7": "نعم، نحن نستخدم تشفير وبروتوكولات أمان قياسية في الصناعة لحماية بياناتك وصورك.",
        "faq.q8": "هل تقدمون دعماً للعملاء؟",
        "faq.a8": "نعم، نحن نقدم دعماً عبر البريد الإلكتروني لجميع المستخدمين ودعماً ذا أولوية لأعضاء PRO لدينا.",
        "gallery.cta": "جرب هذا الطراز",
        "hero.new_title_1": "أكثر من 2 مليون غرفة تمت إعادة تصميمها.",
        "hero.new_title_2": "تصميمك القادم في ثانية واحدة",
        "hero.new_subtitle": "قم بتحميل صورة وشاهد السحر في الوقت الحقيقي. حول أي مساحة باستخدام ذكاء اصطناعي احترافي.",
        "hero.pill.free": "مجاني",
        "hero.pill.no_reg": "بدون تسجيل",
        "hero.pill.one_sec": "ثانية واحدة",
        "hero.cta_main": "حول مساحتك الآن",
        "gallery.new_title": "تحولات ملهمة",
        "gallery.new_subtitle": "غرفتك قد تكون التالية.",
        "gallery.filter.all": "الكل",
        "gallery.filter.kitchens": "مطابخ",
        "gallery.filter.bedrooms": "غرف نوم",
        "gallery.filter.bathrooms": "حمامات",
        "gallery.filter.living": "غرف معيشة",
        "gallery.badge.popular": "الأكثر شيوعاً",
        "gallery.badge.wow": "عامل الإبهار",
        "gallery.badge.elegant": "طراز أنيق",
        "gallery.badge.modern": "حداثي",
        "gallery.label.before": "قبل",
        "gallery.label.after": "بعد (AI)",
        "gallery.cta_try": "جرب هذا الطراز",
        "styles.multi.title": "لا تحصر نفسك في طراز واحد",
        "styles.multi.subtitle": "نفس الحمام. 3 طرز مختلفة.",
        "styles.multi.before": "الأصل",
        "styles.multi.after": "بعد",
        "styles.multi.cta": "جرب بصورتي",
        "dashboard.templates.or_start": "أو ابدأ بنموذج",
        "dashboard.templates.living": "غرفة المعيشة",
        "dashboard.templates.bedroom": "غرفة النوم",
        "dashboard.templates.room": "غرفة فارغة",
        "dashboard.templates.kitchen": "مطبخ قديم",
        "dashboard.styles.choose_title": "اختر النمط",
        "dashboard.form.prompt_label": "صف ما تريد (اختياري)",
        "dashboard.form.prompt_placeholder": "غرفة معيشة بسيطة حديثة مع أثاث أبيض...",
        "dashboard.form.generate_btn": "توليد التصميم",
        "dashboard.form.analyzing": "جاري تحليل المساحة...",
        "dashboard.preview.start_new": "بدء جديد",
        "dashboard.preview.download": "تحميل التصميم",
        "dashboard.upload.click": "انقر للتحميل",
        "dashboard.upload.drag": "أو قم بسحب وإسقاط صورتك هنا",
        "dashboard.upload.change": "تغيير الصورة",
        "dashboard.preview.empty": "رائعتك ستظهر هنا",
        "dashboard.community.title": "إلهامات المجتمع",
        "dashboard.community.empty_hint": "لا يوجد سجل حتى الآن. ابدأ التصميم لرؤية عملك هنا!",
        "dashboard.teaser.title": "افتح تصميمك الاحترافي",
        "dashboard.teaser.subtitle": "تحفتك الفنية جاهزة. قم بالترقية إلى PRO لعرض النتيجة عالية الجودة على الفور.",
        "dashboard.teaser.button": "افتح التصميم الآن",
    },
};

const LanguageContext = createContext<TranslationContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            <div dir={language === 'ar' ? 'rtl' : 'ltr'}>
                {children}
            </div>
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
