"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en';

interface TranslationContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        "nav.render": "Render",
        "nav.inpaint": "Inpaint",
        "nav.upscale": "Upscale",
        "nav.pricing": "Pricing",
        "nav.faq": "FAQ",
        "nav.upgrade": "Upgrade to PRO",
        "nav.furniture": "Furniture",
        "nav.color": "Color Match",
        "nav.magic": "Magic Editor",
        "magic.title": "Magic Editor",
        "magic.subtitle": "Edit your room with natural language",
        "magic.placeholder": "Describe what to change (e.g. 'remove the rug', 'make walls blue')",
        "magic.generate": "Magic Edit",
        "magic.upload_label": "Upload Room Photo",
        "color.title": "Color Match",
        "color.subtitle": "Instantly change your room's color palette",
        "color.palette_label": "Select Palette",
        "color.upload_label": "Upload Room Photo",
        "color.generate": "Apply Colors",
        "color.custom_prompt": "Custom colors (e.g. 'navy blue and gold')",
        "furniture.title": "Furniture Placement",
        "furniture.subtitle": "Add objects to your room naturally",
        "furniture.room_label": "Room Photo",
        "furniture.object_label": "Furniture Object",
        "furniture.generate": "Place Object",
        "furniture.upload_room": "Upload main room photo",
        "furniture.upload_object": "Upload furniture photo",
        "furniture.prompt_hint": "E.g. Place this chair in the corner...",
        "hero.title": "Your Dream Room in Seconds",
        "hero.subtitle": "Transform your space with AI. Upload a photo and see the magic happen instantly.",
        "hero.upload": "Transform My Room",
        "stats.users": "Happy Users",
        "stats.redesigns": "Room Redesigns",
        "features.title": "Why RoomCraft App?",
        "features.subtitle": "Experience the future of interior design with our powerful AI features.",
        "pricing.title": "Simple, Transparent Pricing",
        "pricing.desc": "Choose the plan that fits your needs",
        "pricing.mostPopular": "Most Popular",
        "pricing.weekly": "Weekly Unlimited",
        "pricing.monthly": "Monthly Unlimited",
        "pricing.yearly": "Yearly Unlimited",
        "btn.startTrial": "Start 3-Day Free Trial",
        "faq.title": "Frequently Asked Questions",
        "footer.product": "Product",
        "footer.company": "Company",
        "footer.legal": "Legal",
        "footer.connect": "Connect",
        "styles.title": "Choose Your Style",
        "styles.modern": "Modern Minimalist",
        "styles.scandinavian": "Scandinavian",
        "styles.industrial": "Industrial",
        "styles.midcentury": "Mid-Century Modern",
        "styles.bohemian": "Bohemian",
        "styles.coastal": "Coastal Mediterranean",
        "styles.farmhouse": "Rustic Farmhouse",
        "styles.artdeco": "Luxury Art Deco",
        "styles.japanese": "Japanese Zen",
        "styles.mediterranean": "Mediterranean",
        "styles.rustic": "Rustic",
        "styles.contemporary": "Contemporary",
        "styles.japandi": "Japandi",
        "styles.dark": "Minimalist Dark",
        "styles.retro": "Retro 70s",
        "features.f1.title": "Every Space. Every Style.",
        "features.f1.desc": "From living rooms to gardens. Modern to vintage. Your vision, instantly visualized.",
        "features.f2.title": "Professional Quality",
        "features.f2.desc": "Export in stunning 4K resolution. Ready for presentations or social media.",
        "features.f3.title": "Real-Time Preview",
        "features.f3.desc": "Watch your space transform before your eyes. No waiting, no guessing.",
        "gallery.title": "Real Transformations",
        "gallery.desc": "See what others have created in seconds",
        "gallery.indicator": "designs generated in the last hour",
        "testimonials.title": "Loved by Designers & Homeowners",
        "testimonials.subtitle": "See what our community has to say",
        "testimonials.t1.name": "Sarah Mitchell",
        "testimonials.t1.role": "Interior Designer",
        "testimonials.t1.location": "New York, USA",
        "testimonials.t1.content": "This tool has completely transformed how I present concepts to clients. The AI generates stunning visuals in seconds that would take me hours to create manually.",
        "testimonials.t2.name": "James Thompson",
        "testimonials.t2.role": "Real Estate Agent",
        "testimonials.t2.location": "London, UK",
        "testimonials.t2.content": "Game changer for staging virtual tours. My listings now showcase potential transformations instantly. Clients love seeing what spaces could become.",
        "testimonials.t3.name": "Carlos Rodríguez",
        "testimonials.t3.role": "Architect",
        "testimonials.t3.location": "Buenos Aires, Argentina",
        "testimonials.t3.content": "Incredible tool for visualizing projects. My clients are impressed with the quality and speed of the renders. Totally recommended!",
        "controls.upload.title": "Upload a photo",
        "controls.upload.tips": "Tips 💡",
        "controls.upload.ready": "Ready to render",
        "controls.upload.button": "Upload a file",
        "controls.upload.desc": "Click to select or drag & drop. JPG, PNG up to 10MB",
        "controls.settings.roomType": "Select room type",
        "controls.settings.commercial": "Commercial",
        "controls.settings.residential": "Residential",
        "controls.settings.perspective": "Perspective",
        "controls.settings.interior": "Interior",
        "controls.settings.exterior": "Exterior",
        "controls.settings.aesthetic": "Design Aesthetic",
        "controls.settings.promptLabel": "Additional Prompt (Optional)",
        "controls.settings.promptPlaceholder": "Write your prompt here...",
        "controls.btn.rendering": "Rendering...",
        "controls.btn.render": "Render Interior",
        "styles.cyberpunk": "Cyberpunk Neon",
        "styles.tropical": "Tropical Oasis",
        "preview.scanning": "Scanning...",
        "preview.processing": "AI PROCESSING",
        "preview.geometry": "Scanning geometry...",
        "preview.noResults": "No Results Yet",
        "preview.desc": "Fill in the form on the left by uploading an image and selecting a style to generate your first interior.",
        "gallery.dashboard.title": "Renders Gallery",
        "gallery.view": "View",
        "gallery.search_placeholder": "Search your designs...",
        "gallery.filter.all": "All",
        "gallery.filter.render": "Renders",
        "gallery.filter.furniture": "Furniture",
        "gallery.filter.color": "Color",
        "gallery.filter.magic": "Magic",
        "gallery.delete_confirm": "Are you sure you want to delete this design?",
        "gallery.delete_btn": "Delete",
        "gallery.cancel_btn": "Cancel",
        "gallery.empty": "No renders yet. Create your first design to see it here!",
        "hero.viewExamples": "View Examples",
        "hero.trust.users": "users",
        "hero.trust.rooms": "rooms redesigned",
        "hero.trust.rating": "rating",
        "hero.rendering": "Rendering your future home...",
        "pricing.f.unlimited": "Unlimited generations",
        "pricing.f.4k": "4K quality exports",
        "pricing.f.allRooms": "All room types",
        "pricing.f.emailSupport": "Email support",
        "pricing.f.everythingWeekly": "Everything in Weekly",
        "pricing.f.priority": "Priority processing",
        "pricing.f.styles": "32+ design styles",
        "pricing.f.prioritySupport": "Priority support",
        "pricing.f.team": "Team collaboration",
        "pricing.f.everythingMonthly": "Everything in Monthly",
        "pricing.f.customAi": "Custom AI training",
        "pricing.f.api": "API access",
        "pricing.f.dedicatedSupport": "Dedicated support",
        "pricing.f.whiteLabel": "White-label option",
        "pricing.desc.weekly": "Perfect for trying out",
        "pricing.desc.monthly": "Most popular choice",
        "pricing.desc.yearly": "Best value",
        "pricing.trial": "3-DAY FREE TRIAL",
        "pricing.savings": "SAVE 60%",
        "pricing.faq.q1": "Can I cancel anytime?",
        "pricing.faq.a1": "Yes, cancel with one click",
        "pricing.faq.q2": "What happens after trial?",
        "pricing.faq.a2": "Nothing. We'll notify you first",
        "pricing.faq.q3": "Do you offer refunds?",
        "pricing.faq.a3": "Full refund within 3 days",
        "faq.subtitle": "Everything you need to know about RoomCraft App",
        "faq.cta.text": "Still have questions?",
        "faq.cta.btn": "Contact our support team",
        "faq.q1": "How does RoomCraft App work?",
        "faq.a1": "Simply upload a photo of your room, select a design style, and our AI will generate a photorealistic redesign of your space in seconds.",
        "faq.q2": "Is there a free trial?",
        "faq.a2": "Yes! We offer a 3-day free trial on our Monthly and Yearly plans so you can experience the full power of RoomCraft App.",
        "faq.q3": "Can I cancel my subscription?",
        "faq.a3": "Absolutely. You can cancel your subscription at any time through your account settings or by contacting our support.",
        "faq.q4": "What file formats are supported?",
        "faq.a4": "We support JPG and PNG files up to 10MB in size for room uploads.",
        "faq.q5": "Can I use the designs commercially?",
        "faq.a5": "Yes, our PRO plans include commercial licenses for all generated designs.",
        "faq.q6": "How many renders can I generate?",
        "faq.a6": "Our PRO plans offer unlimited generations. Free users are subject to a daily limit.",
        "faq.q7": "Is my data secure?",
        "faq.a7": "Yes, we use industry-standard encryption and security protocols to protect your data and photos.",
        "faq.q8": "Do you offer customer support?",
        "faq.a8": "Yes, we offer email support for all users and priority support for our PRO members.",
        "gallery.cta": "Try this style",
        "hero.new_title_1": "2M+ Rooms Redesigned.",
        "hero.new_title_2": "Your Next Design in 1 Second",
        "hero.new_subtitle": "Upload a photo and watch the magic in real-time. Transform any space with professional-grade AI.",
        "hero.pill.free": "Free",
        "hero.pill.no_reg": "No registration",
        "hero.pill.one_sec": "1 second",
        "hero.cta_main": "Transform Your Space Now",
        "gallery.new_title": "Inspirational Transformations",
        "gallery.new_subtitle": "Your room could be next.",
        "gallery.filter.kitchens": "Kitchens",
        "gallery.filter.bedrooms": "Bedrooms",
        "gallery.filter.bathrooms": "Bathrooms",
        "gallery.filter.living": "Living Rooms",
        "gallery.badge.popular": "MOST POPULAR",
        "gallery.badge.wow": "WOW FACTOR",
        "gallery.badge.elegant": "ELEGANT STYLE",
        "gallery.badge.modern": "MODERNIST",
        "gallery.label.before": "Before",
        "gallery.label.after": "After (AI)",
        "gallery.cta_try": "Try This Style",
        "styles.multi.title": "Don't Limit Yourself to One Style",
        "styles.multi.subtitle": "Same room. 3 different styles.",
        "styles.multi.before": "Original",
        "styles.multi.after": "AFTER",
        "styles.multi.cta": "Try With My Photo",
        "dashboard.templates.or_start": "Or Start with a Template",
        "dashboard.templates.living": "Living Room",
        "dashboard.templates.bedroom": "Bedroom",
        "dashboard.templates.room": "Empty Room",
        "dashboard.templates.kitchen": "Old Kitchen",
        "dashboard.styles.choose_title": "Choose Style",
        "dashboard.form.prompt_label": "Describe what you want (Optional)",
        "dashboard.form.prompt_placeholder": "Modern minimalist living room with white furniture...",
        "dashboard.form.generate_btn": "Generate Design",
        "dashboard.form.analyzing": "Analyzing space...",
        "loader.scanning": "Scanning environment...",
        "loader.processing": "Processing room structure...",
        "loader.generating": "Generating your design...",
        "loader.finalizing": "Finalizing touches...",
        "dashboard.preview.start_new": "Start New",
        "dashboard.preview.download": "Download Design",
        "dashboard.upload.click": "Click to Upload",
        "dashboard.upload.drag": "or drag and drop your photo here",
        "dashboard.upload.change": "Change Photo",
        "dashboard.preview.empty": "Your masterpiece will appear here",
        "dashboard.community.title": "Community Inspirations",
        "dashboard.community.empty_hint": "No history yet. Start designing to see your work here!",
        "dashboard.teaser.title": "Unlock Your Professional Design",
        "dashboard.teaser.subtitle": "Your masterpiece is ready. Upgrade to PRO to view the high-quality result instantly.",
        "dashboard.teaser.button": "Unlock Design Now",
        "dashboard.form.step": "Step",
        "dashboard.nav.tools": "Tools",
        "dashboard.nav.create": "Create",
        "dashboard.nav.discover": "Discover",
        "dashboard.nav.profile": "Profile",
        "dashboard.nav.logout": "Logout",
        "dashboard.nav.support": "Support",
    }
};

const LanguageContext = createContext<TranslationContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    useEffect(() => {
        // Enforce English
        setLanguage('en');
    }, []);

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
